name: Deploy V2Ray to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Koyeb
        uses: koyeb/koyeb-action@v1
        with:
          api_token: ${{ secrets.4o6uewiq9qwl0rv6eguzevzaj8lcx05oj1lo1epdcll63ptq7l22f0tbtfuc0a6f }}

      - name: Deploy
        run: |
          koyeb app deploy --name v2ray-server --image v2fly/v2fly-core:latest --region paris
